### ISSUE TITLE
Homeassistant Project

### ISSUE THREAD

**Issue by EliSchleifer** [nahuellofeudo/openhab2-rollease-binding#1]
Sweet progress. I was going to undertake a python port for HomeAssistant. Did you capture your network traffic into a file you can share. Interested inhelping with the reverse eng job.

Also how did you determine the port - 12416 - is that fixed you think or dynamic to each hub?

**Comment by nahuellofeudo** [comment]
HI!

I just captured the traffic by running tcpdump on my access point (a Unifi AP, which runs Linux).
Unfortunately I don't have any pcap files anymore, but feel free to use the descriptions and code in this repository. 
The good stuff is in src/main/java/com/nahuellofeudo/rolleasecontroller. The rest is the interface with OpenHab. You should be able to see the format of most messages in the Controller class.
Email me directly if you want to collaborate (nlofeudo@gmail.com). I don't check this very often, as you can see.

**Comment by nahuellofeudo** [comment]
I'm going to close this "issue" now.
